# Generated by Django 2.0.4 on 2018-11-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserva', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicicleta',
            name='Stock',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
