# Generated by Django 2.0.4 on 2018-11-13 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reserva', '0005_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalles_reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.PositiveIntegerField()),
                ('Bicicleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reserva.Bicicleta')),
                ('Reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reserva.Sucursal')),
            ],
        ),
    ]
