# Generated by Django 2.0.4 on 2018-11-16 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Reserva', '0006_detalles_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='User',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='reserva_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
