# Generated by Django 2.0.4 on 2018-11-17 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reserva', '0007_reserva_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalles_reserva',
            name='Reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reserva.Reserva'),
        ),
    ]
