# Generated by Django 2.0.4 on 2018-11-17 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Reserva', '0008_auto_20181117_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta_credito',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tarjeta_credito_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
