# Generated by Django 2.0.4 on 2018-11-19 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reserva', '0011_detalles_accesorios'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicicleta',
            name='Sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bicicleta_fin', to='Reserva.Sucursal'),
            preserve_default=False,
        ),
    ]
